### ISSUE TITLE
Making Example OBJDIR

### ISSUE THREAD

**Issue by BrettCleary** [hugoam/mud-sample#2]
Hello I am trying to build the mud-examples on Windows 10. Genie generates the appropriate makefiles, but mingw32-make config=debug64 -j8 generates “The system cannot find the path specified” errors for me. I believe the issue is with the paths generated in the makefiles.

The make files are looking for source files in “$(OBJDIR)/mud/3rdparty/bgfx/3rdparty/fcpp/cpp1.o \” for example with “OBJDIR = ../../win64_mingw-gcc/obj/x64/Debug/fcpp”. 

The actual files are in mud-sample/mud/3rdparty/bgfx/3rdparty/fcpp/cpp1.o. I looked through the lua scripts genie uses but couldn’t find where OBJDIR was getting its value from.

Where can I edit the lua script so that genie generates “OBJDIR = ../../mud-sample”? Is this the appropriate way of dealing with this issue?

**Comment by hugoam** [comment]
Hey ! I never tried the mingw/makefiles/windows combination with GENie. I default to Visual Studio on windows.
I know GENie has a command called `objdir` : https://github.com/bkaradzic/GENie/blob/master/docs/scripting-reference.md#objdirpath
However I *think* the default setup GENie generates *should* work without setting the `objdir` explicitly, so I'm wondering if there is something else wrong with your setup.
The fact that the object files end up outside of the build folder is definitely wrong : they are expected to go somewhere under the build folder `build/win64_mingw-gcc/obj/...`

**Comment by BrettCleary** [comment]
Appreciate the response. I would much rather use Visual Studio. I was doing my best to follow your build instructions first before trying to get it set up there. 

I'll see if I can get it working in Visual Studio. Any tips would be helpful. I am not well versed in GENie.

**Comment by hugoam** [comment]
Hey ! Yep to build it with visual studio just run GENie like so : 
```
mud\bin\genie vs2015
```
Should work out of the box without touching anything. Just open the solution and build it, and try one of the numbered examples.

**Comment by hugoam** [comment]
If you got any questions you want an anwser/help real time, I keep in eye on gitter very often: 
https://gitter.im/hugoam/mud
